# Generated by Django 3.1.5 on 2021-04-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_auto_20210318_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_of_roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='yyyy-mm-ddd', verbose_name='date')),
                ('time_start', models.TimeField(blank=True, help_text='HH:MM', null=True)),
                ('time_end', models.TimeField(blank=True, help_text='HH:MM', null=True)),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus')),
            ],
        ),
    ]
